services:
  db:
    env_file: .env
    image: postgres:15-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    env_file: .env
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      - db
    ports:
      - "4000:4000"

volumes:
  pgdata:

networks:
  mai_network:
