version: '3'
services:
  web:
    build:
      context: ../
      dockerfile: ./.devcontainer/Dockerfile
    command: sleep infinity
    volumes:
      - ..:/M.ai:cached
    ports:
      - 4000:4000
      - 4001:4001

  livebook:
    image: ghcr.io/livebook-dev/livebook:0.12.1
    environment:
      # secrets - values are set in '.env'. It's not in version control, but look at 'env'
      LIVEBOOK_PASSWORD: ${LIVEBOOK_PASSWORD}
      LIVEBOOK_DEFAULT_RUNTIME: attached:test@web:mycookie
    volumes:
      - ..:/data
    ports:
      - 8080:8080
      - 8081:8081
